[swarm]
name = "deepseek_demo"
graph_file = "graph.py"
agent_files = [
  "agents/planner.py",
  "agents/publisher.py",
]
skill_files = [
  "skills/planner.prompt.md",
  "skills/publisher.prompt.md",
  "skills/auditor.prompt.md",
]
tool_files = [
  "tools.agent_manager_tool",
  "tools.graph_editor_tool",
  "tools.echo_tool",
  "tools.file_writer_tool",
]

[llm.default]
name = "deepseek"
provider = "openai"
api_url = "https://api.deepseek.com"
api_key = "sk-ec34b2d43c7c4ae6a30b0c0c9350f0c1"
model = "deepseek-reasoner"
